// src/constants/localization.ts
import { id, enUS } from 'date-fns/locale';

export const locales = { id, en: enUS };

export const translations = {
  id: {
    dashboard: 'Dashboard', transactions: 'Transaksi', settings: 'Pengaturan',
    balanceThisMonth: 'Saldo', todayExpense: 'Hari Ini', monthlySummary: 'Ringkasan Bulanan',
    yearlySummary: 'Ringkasan Tahunan',
    month: 'Bulan', income: 'Pemasukan', expense: 'Pengeluaran',
    prev: 'Prev', next: 'Next', expense7Days: 'Pengeluaran 7 Hari Terakhir',
    categoryBreakdown: 'Breakdown Kategori', budgetCategory: 'Anggaran Kategori',
    noExpenseData: 'Belum ada data pengeluaran bulan ini.', noBudgetData: 'Belum ada anggaran yang ditetapkan.',
    all: 'Semua', filterCategory: 'Filter Kategori', searchPlaceholder: 'Cari berdasarkan catatan...',
    totalIncome: 'Total Pemasukan', totalExpense: 'Total Pengeluaran', noTxData: 'Tidak ada transaksi pada tanggal ini.',
    editTx: 'Edit Transaksi', newTx: 'Transaksi Baru', close: 'Tutup',
    amount: 'Jumlah', categoryLabel: 'Kategori', date: 'Tanggal', noteOptional: 'Catatan (opsional)',
    notePlaceholder: 'misal: kopi, gopay', saveChanges: 'Simpan', addTx: 'Tambah',
    confirmDeleteTitle: 'Hapus Transaksi?', confirmDeleteMsg: (cat: string, amt: string) => `Anda yakin ingin menghapus transaksi ${cat} senilai ${amt}?`,
    cancel: 'Batal', delete: 'Hapus',
    success: 'Sukses', error: 'Error', confirm: 'Konfirmasi', ok: 'OK',
    txUpdated: 'Transaksi berhasil diperbarui.', txAdded: 'Transaksi berhasil ditambahkan.',
    theme: 'Tema', autoTheme: 'Otomatis', light: 'Terang', dark: 'Gelap',
    backupRestore: 'Backup & Restore', loginGoogle: 'Login Google', logout: 'Logout',
    backupSuccess: 'Backup Sukses', backupSuccessMsg: 'Data Anda berhasil disimpan di Google Drive.',
    backupError: 'Backup Gagal', restoreSuccess: 'Restore Sukses', restoreSuccessMsg: 'Data berhasil dipulihkan.',
    restoreError: 'Restore Gagal',
    categories: 'Kategori', manageCatExpense: 'Kategori Pengeluaran', manageCatIncome: 'Kategori Pemasukan',
    addCatPlaceholder: (type: string) => `Tambah kategori ${type}`,
    budget: 'Anggaran', budgetDesc: 'Atur anggaran pengeluaran bulanan',
    language: 'Bahasa', selectLang: 'Pilih Bahasa',
    downloadReport: 'Unduh Laporan', generateReport: 'Buat Laporan', generating: 'Membuat...',
    selectPeriod: 'Pilih Periode', reportFor: 'Laporan untuk', monthlyReport: 'Laporan Bulanan', yearlyReport: 'Laporan Tahunan',
    budgetComparison: 'Perbandingan Anggaran',
    selectYear: 'Pilih Tahun',
  },
  en: {
    dashboard: 'Dashboard', transactions: 'Transactions', settings: 'Settings',
    balanceThisMonth: 'Balance', todayExpense: 'Today', monthlySummary: 'Monthly Summary',
    yearlySummary: 'Yearly Summary',
    month: 'Month', income: 'Income', expense: 'Expense',
    prev: 'Prev', next: 'Next', expense7Days: 'Last 7 Days Expense',
    categoryBreakdown: 'Category Breakdown', budgetCategory: 'Category Budget',
    noExpenseData: 'No expense data for this month yet.', noBudgetData: 'No budget has been set.',
    all: 'All', filterCategory: 'Filter Category', searchPlaceholder: 'Search by note...',
    totalIncome: 'Total Income', totalExpense: 'Total Expense', noTxData: 'No transactions on this date.',
    editTx: 'Edit Transaction', newTx: 'New Transaction', close: 'Close',
    amount: 'Amount', categoryLabel: 'Category', date: 'Date', noteOptional: 'Note (optional)',
    notePlaceholder: 'e.g: coffee, ride', saveChanges: 'Save', addTx: 'Add',
    confirmDeleteTitle: 'Delete Transaction?', confirmDeleteMsg: (cat: string, amt: string) => `Are you sure you want to delete the ${cat} transaction of ${amt}?`,
    cancel: 'Cancel', delete: 'Delete',
    success: 'Success', error: 'Error', confirm: 'Confirm', ok: 'OK',
    txUpdated: 'Transaction updated successfully.', txAdded: 'Transaction added successfully.',
    theme: 'Theme', autoTheme: 'Auto', light: 'Light', dark: 'Dark',
    backupRestore: 'Backup & Restore', loginGoogle: 'Login with Google', logout: 'Logout',
    backupSuccess: 'Backup Successful', backupSuccessMsg: 'Your data has been saved to Google Drive.',
    backupError: 'Backup Failed', restoreSuccess: 'Restore Successful', restoreSuccessMsg: 'Data has been restored.',
    restoreError: 'Restore Failed',
    categories: 'Categories', manageCatExpense: 'Expense Categories', manageCatIncome: 'Income Categories',
    addCatPlaceholder: (type: string) => `Add ${type} category`,
    budget: 'Budget', budgetDesc: 'Set monthly expense budget',
    language: 'Language', selectLang: 'Select Language',
    downloadReport: 'Download Report', generateReport: 'Generate Report', generating: 'Generating...',
    selectPeriod: 'Select Period', reportFor: 'Report for', monthlyReport: 'Monthly Report', yearlyReport: 'Yearly Report',
    budgetComparison: 'Budget Comparison',
    selectYear: 'Select Year',
  }
};
